In [1]:
import pandas as pd

In [19]:
neighborhoods = pd.read_csv("neighborhoods.csv", index_col=[0, 1, 2], header=[0,1])
neighborhoods.columns.names = ["Category", "Subcategory"]
neighborhoods

Category                                       Culture         Services  \
Subcategory                                Restaurants Museums   Police
State City               Street
MO    Fisherborough      244 Tracy View             C+       F       D-
SD    Port Curtisville   446 Cynthia Inlet          C-       B        B
WV    Jimenezview        432 John Common             A      A+        F
AK    Stevenshire        238 Andrew Rue             D-       A       A-
ND    New Joshuaport     877 Walter Neck            D+      C-        B
...                                                ...     ...      ...
MI    North Matthew      055 Clayton Isle           B-       C        B
MT    Chadton            601 Richards Road          A-       D       D+
SC    Diazmouth          385 Robin Harbors           F       D       B-
VA    Laurentown         255 Gonzalez Land          C+      B-        F
NE    South Kennethmouth 346 Wallace Pass           C-      B-        A

Category
Subcategory                                Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [23]:
neighborhoods.sort_index(ascending=[False, True, False]).head(100)

Category                                        Culture         Services  \
Subcategory                                 Restaurants Museums   Police
State City             Street
WY    Hardyburgh       227 Andrew Parkway             D      C-       D-
      Lake Nicole      933 Jennifer Burg              C      A+       A-
                       754 Weaver Turnpike            B      D-        B
      Martintown       013 Bell Mills                C-       D       A-
      Port Jason       624 Faulkner Orchard          A-       F       C+
...                                                 ...     ...      ...
NM    West Ambermouth  785 Kristen Vista             D-      D-       D+
NJ    Lake Annaborough 644 Ronald Square             B+       D       D+
NH    Courtneyfort     697 Spencer Isle              A+      A+       C+
      East Deborahberg 271 Ryan Mount                 B       C       D+
      Ingramton        430 Calvin Underpass          C+      D+        C

Category
Subcategory                                 Schools
State City             Street
WY    Hardyburgh       227 Andrew Parkway         C
      Lake Nicole      933 Jennifer Burg          C
                       754 Weaver Turnpike        D
      Martintown       013 Bell Mills            B-
      Port Jason       624 Faulkner Orchard      C+
...                                             ...
NM    West Ambermouth  785 Kristen Vista         A+
NJ    Lake Annaborough 644 Ronald Square          D
NH    Courtneyfort     697 Spencer Isle          A+
      East Deborahberg 271 Ryan Mount            B-
      Ingramton        430 Calvin Underpass      C-

[100 rows x 4 columns]